AC_DEFUN([AM_PATH_GDK_PIXBUF],
[dnl
  AM_PATH_GTK(,[$2],[$3],[gdk-pixbuf-2.0])
  GDK_PIXBUF_CFLAGS="$GTK_CFLAGS"
  GDK_PIXBUF_LIBS="$GTK_LIBS"
  AC_SUBST(GDK_PIXBUF_CFLAGS)
  AC_SUBST(GDK_PIXBUF_LIBS)
])
